// ─── Recipe Data ────────────────────────────────────────────────────────────
// `scalable: false` → ingredient text stays the same regardless of portion
// `textFn: (mult) => string` → custom text per multiplier for descriptive items
// `variants` → array of { id, label, baseIngredients?, filling?, steps?, tips? } — swaps sections
export const retete = [
  {
    id: "cozonac",
    name: "Cozonac Tradițional",
    icon: "🍞",
    description: "Cozonacul pufos, cu miez elastic și coajă aurie, este regele mesei de Paște.",
    prepTime: "PT40M",
    prepLabel: "40 min",
    cookTime: "PT50M",
    cookLabel: "50 min",
    totalTime: "PT4H",
    totalLabel: "~4h (cu dospire)",
    servings: 2,
    servingsUnit: "cozonaci",
    calories: 320,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "zahăr", swap: "200g miere de salcâm (reduce cu 20%)" },
      { match: "făină albă tip 000", swap: "800g făină spelt + 200g făină albă" },
      { match: "unt moale", swap: "120g ulei de cocos topit" },
    ],
    healthyCalories: 265,
    healthyNote: "Mierea și spelt-ul reduc indicele glicemic cu ~25%. Uleiul de cocos înlocuiește grăsimile saturate din unt.",
    tips: [
      "Toate ingredientele trebuie să fie la temperatura camerei.",
      "Frământă aluatul minim 15 minute — cu cât frământi mai mult, cu atât e mai pufos.",
      "Nu deschide cuptorul în primele 30 de minute de coacere.",
      "Testează cu o scobitoare — dacă iese curată, cozonacul e gata.",
    ],
    baseIngredients: [
      { qty: 1, unit: "kg", name: "făină albă tip 000" },
      { qty: 10, unit: "buc", name: "gălbenușuri de ou" },
      { qty: 250, unit: "g", name: "zahăr" },
      { qty: 200, unit: "ml", name: "lapte călduț" },
      { qty: 150, unit: "g", name: "unt moale" },
      { qty: 50, unit: "g", name: "drojdie proaspătă" },
      { qty: 1, unit: "buc", name: "coajă rasă de lămâie", textFn: (m) => m < 1 ? "coajă rasă de la jumătate de lămâie" : m === 1 ? "coajă rasă de lămâie" : `coajă rasă de la ${m} lămâi` },
      { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
      { qty: null, unit: "", name: "sare (un praf)", scalable: false },
    ],
    filling: [
      { qty: 300, unit: "g", name: "nucă măcinată" },
      { qty: 100, unit: "g", name: "zahăr" },
      { qty: 50, unit: "g", name: "cacao" },
      { qty: 3, unit: "linguri", name: "rom alimentar" },
    ],
    steps: [
      { text: "Dizolvă drojdia în laptele călduț cu o linguriță de zahăr. Lasă 10 minute până face spumă.", tip: "Laptele trebuie să fie călduț, nu fierbinte — drojdia moare la peste 40°C." },
      { text: "Amestecă făina cu zahărul și sarea. Adaugă gălbenușurile pe rând, drojdia dizolvată și frământă 15-20 minute.", tip: null },
      { text: "Încorporează untul moale bucată cu bucată, continuă să frământi până aluatul devine elastic și se desprinde de mâini.", tip: "Untul trebuie să fie la temperatura camerei, nu topit." },
      { text: "Adaugă coaja de lămâie și vanilia. Acoperă cu un prosop și lasă la dospit 1-2 ore (până se dublează).", tip: "Pune bolul într-un loc cald, fără curenți." },
      { text: "Prepară umplutura: amestecă nuca cu zahărul, cacaua și romul.", tip: null },
      { text: "Întinde aluatul în dreptunghi, presară umplutura uniform, apoi rulează strâns.", tip: "Nu presăra umplutura până la margini — lasă 2cm liberi." },
      { text: "Așează ruloul în tavă unsă cu unt și tapetată cu făină. Lasă la dospit încă 30-40 minute.", tip: null },
      { text: "Unge cu gălbenuș bătut cu puțin lapte. Coace la 170°C pentru 45-50 minute.", tip: "Pune tava pe raftul de jos al cuptorului." },
      { text: "Scoate din cuptor, lasă 10 minute în tavă, apoi răstoarnă pe un grătar. Acoperă cu un prosop curat.", tip: null },
    ],
    variants: [
      { id: "nuca-cacao", label: "Cu Nucă și Cacao" },
      {
        id: "rahat",
        label: "Cu Rahat",
        filling: [
          { qty: 500, unit: "g", name: "rahat (tăiat fâșii)" },
        ],
        stepsOverride: { 4: { text: "Taie rahatul în fâșii lungi — se vor folosi ca umplutură.", tip: null } },
      },
      {
        id: "mac",
        label: "Cu Mac",
        filling: [
          { qty: 300, unit: "g", name: "mac măcinat" },
          { qty: 100, unit: "g", name: "zahăr" },
          { qty: 50, unit: "ml", name: "lapte" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
        ],
        stepsOverride: { 4: { text: "Prepară umplutura: fierbe macul cu laptele și zahărul 5 minute, apoi adaugă vanilia.", tip: null } },
      },
      {
        id: "ciocolata",
        label: "Cu Ciocolată",
        filling: [
          { qty: 300, unit: "g", name: "ciocolată neagră (topită)" },
          { qty: 100, unit: "g", name: "nucă măcinată" },
          { qty: 50, unit: "g", name: "unt" },
        ],
        stepsOverride: { 4: { text: "Prepară umplutura: topește ciocolata cu untul la bain-marie, amestecă cu nuca.", tip: "Nu lăsa ciocolata pe foc direct — se arde." } },
      },
      {
        id: "vegan",
        label: "Vegan",
        baseIngredients: [
          { qty: 1, unit: "kg", name: "făină albă tip 000" },
          { qty: 250, unit: "ml", name: "lapte vegetal (ovăz sau soia)" },
          { qty: 150, unit: "ml", name: "ulei de cocos topit" },
          { qty: 250, unit: "g", name: "zahăr" },
          { qty: 50, unit: "g", name: "drojdie proaspătă" },
          { qty: 1, unit: "buc", name: "coajă rasă de lămâie", textFn: (m) => m < 1 ? "coajă rasă de la jumătate de lămâie" : m === 1 ? "coajă rasă de lămâie" : `coajă rasă de la ${m} lămâi` },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: null, unit: "", name: "sare (un praf)", scalable: false },
        ],
        tips: ["Laptele vegetal de soia dă cel mai pufos aluat.", "Uleiul de cocos trebuie topit dar nu fierbinte."],
      },
      {
        id: "fara-gluten",
        label: "Fără Gluten",
        baseIngredients: [
          { qty: 600, unit: "g", name: "mix făină fără gluten (Schar sau similar)" },
          { qty: 400, unit: "g", name: "făină de orez" },
          { qty: 10, unit: "buc", name: "gălbenușuri de ou" },
          { qty: 250, unit: "g", name: "zahăr" },
          { qty: 200, unit: "ml", name: "lapte călduț" },
          { qty: 150, unit: "g", name: "unt moale" },
          { qty: 7, unit: "g", name: "drojdie uscată activă (de 2 ori doza normală)" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: null, unit: "", name: "sare (un praf)", scalable: false },
        ],
        tips: ["Aluatul fără gluten e mai lipicios — nu adăuga mai multă făină.", "Dospirea e mai lentă — lasă 3 ore."],
      },
    ],
  },
  {
    id: "drob",
    name: "Drob de Miel",
    icon: "🐑",
    description: "Drobul este vedeta absolută a mesei de Paște. Aromat, suculent și plin de savoare.",
    prepTime: "PT30M",
    prepLabel: "30 min",
    cookTime: "PT60M",
    cookLabel: "60 min",
    totalTime: "PT1H30M",
    totalLabel: "~1.5h",
    servings: 8,
    servingsUnit: "porții",
    calories: 280,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "lapte", swap: "lapte de migdale neîndulcit" },
      { match: "ulei de măsline", swap: "2 linguri ulei de măsline (redus la jumătate)" },
      { match: "pesmet", swap: "pesmet din pâine integrală" },
    ],
    healthyCalories: 235,
    healthyNote: "Drobul e deja bogat în proteine și fier. Reducerile aduc cu ~15% mai puține calorii.",
    tips: [
      "Organele se pot trece prin mașina de tocat pentru textură mai fină.",
      "Drobul e mai gustos a doua zi, servit rece.",
      "Poți adăuga și măduvă de miel pentru un plus de savoare.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "organe de miel (ficat, inimă, plămâni, rinichi)" },
      { qty: 4, unit: "buc", name: "ouă" },
      { qty: 2, unit: "buc", name: "cepe mari" },
      { qty: 1, unit: "legătură", name: "mărar proaspăt" },
      { qty: 1, unit: "legătură", name: "pătrunjel proaspăt" },
      { qty: 1, unit: "legătură", name: "lob (leuștean)" },
      { qty: 3, unit: "linguri", name: "ulei de măsline" },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
      { qty: 100, unit: "ml", name: "lapte" },
      { qty: 2, unit: "linguri", name: "pesmet" },
    ],
    filling: [],
    steps: [
      { text: "Spală bine organele și fierbe-le în apă cu sare 20-25 de minute. Scurge și lasă să se răcească.", tip: "Schimbă apa o dată în timpul fierberii pentru un gust mai curat." },
      { text: "Taie organele în cubulețe mici sau trece-le prin mașina de tocat (textură mai fină).", tip: null },
      { text: "Călește ceapa tăiată mărunt în ulei până devine translucidă.", tip: null },
      { text: "Amestecă organele tocate cu ceapa călită, verdețurile tăiate fin, ouăle bătute, laptele, sarea și piperul.", tip: null },
      { text: "Unge o tavă de cozonac cu ulei și presară pesmet pe fund și pereți.", tip: null },
      { text: "Toarnă compoziția în tavă. Decorează deasupra cu felii de ou fiert și frunze de verdeață.", tip: "Ouăle fierte tăiate în rondele arată spectaculos la tăiere." },
      { text: "Coace la 180°C pentru 45-50 minute, până devine auriu deasupra.", tip: null },
      { text: "Lasă să se răcească complet în tavă înainte de a tăia felii. Se servește rece sau la temperatura camerei.", tip: null },
    ],
    variants: [
      { id: "miel", label: "De Miel" },
      {
        id: "pui",
        label: "De Pui",
        baseIngredients: [
          { qty: 500, unit: "g", name: "ficat de pui" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 2, unit: "buc", name: "cepe mari" },
          { qty: 1, unit: "legătură", name: "mărar proaspăt" },
          { qty: 1, unit: "legătură", name: "pătrunjel proaspăt" },
          { qty: 3, unit: "linguri", name: "ulei de măsline" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 100, unit: "ml", name: "lapte" },
          { qty: 2, unit: "linguri", name: "pesmet" },
        ],
      },
      {
        id: "porc",
        label: "De Porc",
        baseIngredients: [
          { qty: 500, unit: "g", name: "ficat și rinichi de porc" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 2, unit: "buc", name: "cepe mari" },
          { qty: 1, unit: "legătură", name: "mărar proaspăt" },
          { qty: 1, unit: "legătură", name: "pătrunjel proaspăt" },
          { qty: 3, unit: "linguri", name: "ulei" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 100, unit: "ml", name: "lapte" },
          { qty: 2, unit: "linguri", name: "pesmet" },
          { qty: 100, unit: "g", name: "slănină afumată (cubulețe)" },
        ],
      },
      {
        id: "vegetarian",
        label: "Vegetarian",
        baseIngredients: [
          { qty: 400, unit: "g", name: "ciuperci brune (tocate fin)" },
          { qty: 200, unit: "g", name: "linte roșie (fiartă)" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 2, unit: "buc", name: "cepe mari" },
          { qty: 1, unit: "legătură", name: "mărar proaspăt" },
          { qty: 1, unit: "legătură", name: "pătrunjel proaspăt" },
          { qty: 3, unit: "linguri", name: "ulei de măsline" },
          { qty: null, unit: "", name: "sare, piper și boia după gust", scalable: false },
          { qty: 100, unit: "ml", name: "lapte vegetal sau normal" },
          { qty: 2, unit: "linguri", name: "pesmet" },
        ],
        steps: [
          { text: "Călește ciupercile în ulei la foc mare până scade toată apa (8-10 minute).", tip: "Nu sări acest pas — ciupercile apoase strica textura." },
          { text: "Adaugă ceapa tocată și mai călește 3 minute.", tip: null },
          { text: "Amestecă ciupercile cu lintea fiartă, ouăle bătute, verdețurile, laptele, sarea și piperul.", tip: null },
          { text: "Unge o tavă cu ulei și presară pesmet. Toarnă compoziția.", tip: null },
          { text: "Decorează cu felii de ou fiert și roșii cherry.", tip: null },
          { text: "Coace la 180°C pentru 40-45 minute.", tip: null },
          { text: "Lasă să se răcească complet. Se servește rece.", tip: null },
        ],
        tips: ["Ciupercile și lintea trebuie bine scurse.", "Adaugă 1 lingură de sos de soia pentru savoare extra."],
      },
    ],
  },
  {
    id: "pasca",
    name: "Pască cu Brânză Dulce",
    icon: "🧀",
    description: "Pască tradițională cu brânză dulce de vaci, stafide și vanilie — desertul preferat alături de cozonac.",
    prepTime: "PT30M",
    prepLabel: "30 min",
    cookTime: "PT45M",
    cookLabel: "45 min",
    totalTime: "PT3H",
    totalLabel: "~3h (cu dospire)",
    servings: 10,
    servingsUnit: "porții",
    calories: 290,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "zahăr", swap: "100g eritritol (zero calorii)" },
      { match: "smântână", swap: "100g iaurt grecesc 0% grăsime" },
      { match: "griș", swap: "50g fulgi de ovăz fin măcinați" },
    ],
    healthyCalories: 195,
    healthyNote: "Eritritolul nu afectează glicemia. Iaurtul grec adaugă proteine și reduce grăsimile cu 60%.",
    tips: [
      "Brânza de vaci trebuie scursă foarte bine — pune-o într-un tifon și lasă 2-3 ore.",
      "Stafidele se înmoaie în rom sau apă caldă 15 minute înainte.",
      "Nu deschide cuptorul devreme — pașca se lasă la mijloc.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "brânză dulce de vaci (scursă bine)" },
      { qty: 4, unit: "buc", name: "ouă" },
      { qty: 150, unit: "g", name: "zahăr" },
      { qty: 100, unit: "g", name: "stafide" },
      { qty: 100, unit: "g", name: "smântână" },
      { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
      { qty: 1, unit: "buc", name: "coajă rasă de lămâie", textFn: (m) => m < 1 ? "coajă rasă de la jumătate de lămâie" : m === 1 ? "coajă rasă de lămâie" : `coajă rasă de la ${m} lămâi` },
      { qty: 50, unit: "g", name: "griș" },
    ],
    filling: [],
    steps: [
      { text: "Pregătește aluatul de cozonac (sau folosește aluat gata de pască). Tapetează o formă rotundă cu aluat pe fund și margini.", tip: null },
      { text: "Mixează brânza de vaci cu zahărul până devine cremoasă.", tip: "Folosește un mixer pentru o textură cât mai fină." },
      { text: "Adaugă ouăle pe rând, mestecând după fiecare. Apoi smântâna, vanilia și coaja de lămâie.", tip: null },
      { text: "Încorporează grișul și stafidele (înmuiate 10 minute în apă caldă și scurse).", tip: null },
      { text: "Toarnă compoziția de brânză peste aluatul din formă.", tip: null },
      { text: "Decorează deasupra cu benzi de aluat în formă de cruce sau grilaj.", tip: "Aluatul de decor se subțiază și se aranjează frumos." },
      { text: "Unge cu gălbenuș bătut. Coace la 170°C pentru 40-45 minute, până devine aurie.", tip: null },
      { text: "Lasă să se răcească complet în formă. Se servește rece, presărată cu zahăr pudră.", tip: null },
    ],
    variants: [
      { id: "stafide", label: "Cu Stafide" },
      {
        id: "fara-stafide",
        label: "Fără Stafide",
        baseIngredients: [
          { qty: 500, unit: "g", name: "brânză dulce de vaci (scursă bine)" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 150, unit: "g", name: "zahăr" },
          { qty: 100, unit: "g", name: "smântână" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: 1, unit: "buc", name: "coajă rasă de lămâie", textFn: (m) => m < 1 ? "coajă rasă de la jumătate de lămâie" : m === 1 ? "coajă rasă de lămâie" : `coajă rasă de la ${m} lămâi` },
          { qty: 50, unit: "g", name: "griș" },
        ],
      },
      {
        id: "ciocolata",
        label: "Cu Ciocolată",
        baseIngredients: [
          { qty: 500, unit: "g", name: "brânză dulce de vaci (scursă bine)" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 150, unit: "g", name: "zahăr" },
          { qty: 100, unit: "g", name: "smântână" },
          { qty: 80, unit: "g", name: "cacao" },
          { qty: 100, unit: "g", name: "ciocolată neagră (topită)" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: 50, unit: "g", name: "griș" },
        ],
      },
    ],
  },
  {
    id: "friptura",
    name: "Friptură la Cuptor",
    icon: "🍖",
    description: "Friptură fragedă la cuptor cu usturoi și rozmarin — piesa centrală a mesei festive de Paște.",
    prepTime: "PT20M",
    prepLabel: "20 min",
    cookTime: "PT2H",
    cookLabel: "2h",
    totalTime: "PT2H30M",
    totalLabel: "~2.5h",
    servings: 6,
    servingsUnit: "porții",
    calories: 350,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "vin alb sec", swap: "150ml supă de legume + suc de lămâie" },
      { match: "ulei de măsline", swap: "2 linguri ulei de măsline (redus)" },
    ],
    healthyCalories: 295,
    healthyNote: "Friptura de miel e excelentă proteic. Fără vin elimini zahărurile fermentate.",
    tips: [
      "Scoate carnea din frigider cu 30 min înainte — se gătește mai uniform.",
      "Unge carnea cu sucul din tavă la fiecare 30 de minute.",
      "Lasă carnea să se odihnească 15 min sub folie înainte de tăiere.",
    ],
    baseIngredients: [
      { qty: 1.5, unit: "kg", name: "pulpă sau spată de miel" },
      { qty: 8, unit: "căței", name: "usturoi" },
      { qty: 3, unit: "ramuri", name: "rozmarin proaspăt" },
      { qty: 3, unit: "linguri", name: "ulei de măsline" },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
      { qty: 2, unit: "buc", name: "cepe mari (tăiate în sferturi)" },
      { qty: 500, unit: "g", name: "cartofi (tăiați în sferturi)" },
      { qty: 200, unit: "ml", name: "vin alb sec" },
      { qty: 1, unit: "buc", name: "suc de lămâie", textFn: (m) => m < 1 ? "suc de la jumătate de lămâie" : m === 1 ? "suc de la o lămâie" : `suc de la ${m} lămâi` },
    ],
    filling: [],
    steps: [
      { text: "Scoate carnea la temperatura camerei cu 30 minute înainte de gătit.", tip: null },
      { text: "Fă tăieturi adânci în carne și introduce felii de usturoi și frunze de rozmarin în fiecare tăietură.", tip: "Fă tăieturile la 3-4 cm distanță una de alta." },
      { text: "Freacă carnea cu ulei de măsline, sare, piper și suc de lămâie.", tip: null },
      { text: "Așează ceapa și cartofii pe fundul tăvii. Pune carnea deasupra.", tip: null },
      { text: "Toarnă vinul în tavă. Acoperă strâns cu folie de aluminiu.", tip: null },
      { text: "Coace la 180°C acoperit timp de 1.5 ore. Apoi scoate folia și crește temperatura la 200°C.", tip: "Tava trebuie acoperită etanș — aburi = carne fragedă." },
      { text: "Coace neacoperit încă 30 minute, ungând ocazional cu sucul din tavă, până se rumenește frumos.", tip: null },
      { text: "Lasă carnea să se odihnească 15 minute acoperită cu folie înainte de a tăia. Servește cu legumele din tavă.", tip: null },
    ],
    variants: [
      { id: "miel", label: "De Miel" },
      {
        id: "pui",
        label: "De Pui",
        baseIngredients: [
          { qty: 1.5, unit: "kg", name: "pui întreg sau pulpe de pui" },
          { qty: 6, unit: "căței", name: "usturoi" },
          { qty: 2, unit: "ramuri", name: "rozmarin proaspăt" },
          { qty: 2, unit: "ramuri", name: "cimbru proaspăt" },
          { qty: 3, unit: "linguri", name: "ulei de măsline" },
          { qty: null, unit: "", name: "sare, boia dulce și piper după gust", scalable: false },
          { qty: 2, unit: "buc", name: "cepe mari (tăiate în sferturi)" },
          { qty: 500, unit: "g", name: "cartofi (tăiați în sferturi)" },
          { qty: 100, unit: "ml", name: "vin alb sec" },
        ],
      },
      {
        id: "porc",
        label: "De Porc",
        baseIngredients: [
          { qty: 1.5, unit: "kg", name: "ceafă sau spată de porc" },
          { qty: 8, unit: "căței", name: "usturoi" },
          { qty: 2, unit: "ramuri", name: "rozmarin proaspăt" },
          { qty: 3, unit: "linguri", name: "ulei" },
          { qty: 2, unit: "linguri", name: "muștar" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 2, unit: "buc", name: "cepe mari (tăiate în sferturi)" },
          { qty: 500, unit: "g", name: "cartofi (tăiați în sferturi)" },
          { qty: 200, unit: "ml", name: "bere blondă" },
        ],
      },
      {
        id: "marinada-lamaie-ierburi",
        label: "Marinadă Lămâie",
        baseIngredients: [
          { qty: 1.5, unit: "kg", name: "pulpă sau spată de miel (sau pui)" },
          { qty: 2, unit: "buc", name: "lămâi (suc și coajă)" },
          { qty: 6, unit: "căței", name: "usturoi (pisat)" },
          { qty: 3, unit: "linguri", name: "ulei de măsline" },
          { qty: 2, unit: "linguri", name: "oregano uscat" },
          { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru" : m === 1 ? "1 lingurită cimbru" : `${Math.round(m)} lingurițe cimbru` },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 2, unit: "buc", name: "cepe mari (tăiate în sferturi)" },
          { qty: 500, unit: "g", name: "cartofi noi (întregi, mici)" },
        ],
        stepsOverride: {
          2: { text: "Pregătește marinada: amestecă sucul și coaja de lămâie cu usturoiul pisat, uleiul, oregano, cimbrul, sare și piper.", tip: "Marinada poate fi pregătită cu o zi înainte pentru gust maxim." },
          3: { text: "Unge bine carnea cu marinada. Lasă minim 2 ore (ideal peste noapte la frigider).", tip: null },
        },
      },
      {
        id: "marinada-miere-mustar",
        label: "Marinadă Miere",
        baseIngredients: [
          { qty: 1.5, unit: "kg", name: "pulpă sau spată de porc (sau pui)" },
          { qty: 3, unit: "linguri", name: "miere" },
          { qty: 2, unit: "linguri", name: "muștar Dijon" },
          { qty: 3, unit: "căței", name: "usturoi (pisat)" },
          { qty: 2, unit: "linguri", name: "sos de soia" },
          { qty: 1, unit: "lingură", name: "ulei de măsline" },
          { qty: null, unit: "", name: "piper după gust", scalable: false },
          { qty: 2, unit: "buc", name: "cepe mari (tăiate în sferturi)" },
          { qty: 500, unit: "g", name: "cartofi (tăiați în sferturi)" },
        ],
        stepsOverride: {
          2: { text: "Pregătește glazura: amestecă mierea cu muștarul, usturoiul pisat, sosul de soia și uleiul.", tip: "Glazura se caramelizează frumos la final — unge carnea des." },
        },
        tips: ["Glazura de miere se arde dacă temperatura e prea mare — ține la 180°C.", "Unge carnea cu glazură la fiecare 20 de minute în ultima oră."],
      },
    ],
  },
  {
    id: "salata-boeuf",
    name: "Salată de Boeuf",
    icon: "🥗",
    description: "Salata de boeuf este nelipsită de pe masa de Paște. Rețeta tradițională cu legume fierte și maioneză.",
    prepTime: "PT45M",
    prepLabel: "45 min",
    cookTime: "PT40M",
    cookLabel: "40 min",
    totalTime: "PT2H",
    totalLabel: "~2h",
    servings: 10,
    servingsUnit: "porții",
    calories: 240,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "maioneză", swap: "150g maioneză light + 150g iaurt grecesc" },
    ],
    healthyCalories: 170,
    healthyNote: "Jumătate maioneză + iaurt = aceeași cremozitate cu 40% mai puțin grăsime.",
    tips: [
      "Fierbe legumele separat — fiecare are alt timp de gătire.",
      "Taie totul în cubulețe mici și egale — textura contează.",
      "Adaugă maioneza treptat — nu pune toată odată.",
      "Lasă salata la rece minim 2 ore înainte de servire.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "piept de pui (sau vită)" },
      { qty: 500, unit: "g", name: "cartofi" },
      { qty: 300, unit: "g", name: "morcovi" },
      { qty: 200, unit: "g", name: "rădăcină de pătrunjel" },
      { qty: 200, unit: "g", name: "mazăre (conservă sau congelată)" },
      { qty: 200, unit: "g", name: "murături asortate (castraveți, gogoșari)" },
      { qty: 4, unit: "buc", name: "ouă fierte" },
      { qty: 300, unit: "g", name: "maioneză" },
      { qty: 2, unit: "linguri", name: "muștar" },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Fierbe pieptul de pui în apă cu sare, un morcov și o frunză de dafin, 30-35 minute. Lasă să se răcească.", tip: null },
      { text: "Fierbe cartofii și morcovii separat, în coajă, până sunt al dente (nu prea moi). Răcește în apă rece.", tip: "Cartofii trecuți de fiert se sfărâmă — verifică cu o scobitoare." },
      { text: "Fierbe ouăle tari (10 minute), răcește-le în apă rece, curăță-le.", tip: null },
      { text: "Taie carnea, cartofii, morcovii, ouăle și murăturile în cubulețe mici (5mm).", tip: "Asta e etapa care durează cel mai mult — pune muzică bună." },
      { text: "Adaugă mazărea scursă și rădăcina de pătrunjel tăiată mărunt.", tip: null },
      { text: "Amestecă maioneza cu muștarul. Încorporează treptat în salată, amestecând delicat.", tip: "Nu pune toată maioneza — păstrează puțin pentru decorare." },
      { text: "Potrivește de sare și piper. Egalează într-un bol sau formă.", tip: null },
      { text: "Decorează cu maioneză, felii de ou, măsline și verdețuri. Refrigerează minim 2 ore.", tip: null },
    ],
    variants: [
      { id: "pui", label: "Cu Pui" },
      {
        id: "vita",
        label: "Cu Vită",
        baseIngredients: [
          { qty: 500, unit: "g", name: "carne de vită (pulpă)" },
          { qty: 500, unit: "g", name: "cartofi" },
          { qty: 300, unit: "g", name: "morcovi" },
          { qty: 200, unit: "g", name: "rădăcină de pătrunjel" },
          { qty: 200, unit: "g", name: "mazăre (conservă sau congelată)" },
          { qty: 200, unit: "g", name: "murături asortate (castraveți, gogoșari)" },
          { qty: 4, unit: "buc", name: "ouă fierte" },
          { qty: 300, unit: "g", name: "maioneză" },
          { qty: 2, unit: "linguri", name: "muștar" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
        ],
      },
    ],
  },
  {
    id: "oua-rosii",
    name: "Ouă Roșii Vopsite Natural",
    icon: "🥚",
    description: "Rețeta tradițională de vopsit ouă cu coji de ceapă — culoare intensă, 100% naturală.",
    prepTime: "PT15M",
    prepLabel: "15 min",
    cookTime: "PT30M",
    cookLabel: "30 min",
    totalTime: "PT1H",
    totalLabel: "~1h",
    servings: 10,
    servingsUnit: "ouă",
    calories: 70,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [],
    healthyCalories: 70,
    healthyNote: "Rețeta e deja 100% naturală! Ouăle sunt sursă excelentă de proteine complete și vitamine B.",
    tips: [
      "Cu cât lași mai multe coji, cu atât roșul e mai intens.",
      "Ouăle trebuie scoase din frigider cu 2 ore înainte — altfel crapă.",
      "Adaugă o lingură de oțet — fixează culoarea.",
      "Pentru luciu, freacă ouăle cu puțin ulei după ce se usucă.",
    ],
    baseIngredients: [
      { qty: 10, unit: "buc", name: "ouă (la temperatura camerei)" },
      { qty: null, unit: "", name: "coji de la 8-10 cepe galbene", scalable: false, textFn: (m) => m <= 0.5 ? "coji de la 4-5 cepe galbene" : m === 1 ? "coji de la 8-10 cepe galbene" : `coji de la ${Math.round(8 * m)}-${Math.round(10 * m)} cepe galbene` },
      { qty: 2, unit: "linguri", name: "oțet alb" },
      { qty: 1, unit: "lingură", name: "ulei (pentru luciu la final)" },
      { qty: null, unit: "", name: "sare (o linguriță)", scalable: false },
      { qty: null, unit: "", name: "apă cât să acopere ouăle", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Adună coji de ceapă galbenă — cu cât mai multe, cu atât culoarea e mai intensă. Pune-le într-o oală mare.", tip: "Poți aduna coji cu câteva zile înainte." },
      { text: "Adaugă apă peste coji cât să le acopere bine. Fierbe 20-30 minute pentru a obține un lichid roșu-brun intens.", tip: null },
      { text: "Strecoară lichidul și pune-l înapoi în oală. Adaugă oțetul și sarea.", tip: null },
      { text: "Pune ouăle (la temperatura camerei!) delicat în lichid. Lichidul trebuie să le acopere.", tip: "Ouăle reci crapă la contact cu lichidul fierbinte." },
      { text: "Fierbe la foc mic 10-12 minute. Pentru culoare mai intensă, lasă ouăle în lichid după stingerea focului.", tip: null },
      { text: "Scoate ouăle cu o lingură și lasă-le pe un grătar sau pe hârtie de bucătărie.", tip: null },
      { text: "După ce s-au răcit complet, freacă fiecare ou cu puțin ulei pe un șervețel — le dă un luciu superb.", tip: null },
    ],
  },
  {
    id: "ciorba-miel",
    name: "Ciorbă de Miel cu Leuștean",
    icon: "🥣",
    description: "Ciorbă tradițională de Paște, acrișoară și aromată, cu carne fragedă și leuștean proaspăt.",
    prepTime: "PT20M",
    prepLabel: "20 min",
    cookTime: "PT1H30M",
    cookLabel: "1.5h",
    totalTime: "PT2H",
    totalLabel: "~2h",
    servings: 8,
    servingsUnit: "porții",
    calories: 210,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "smântână (pentru dresire)", swap: "iaurt grecesc 2% pentru dresire" },
    ],
    healthyCalories: 175,
    healthyNote: "Ciorbă de Paște e ușoară și hrănitoare. Iaurtul înlocuiește smântâna cu mai puține grăsimi.",
    tips: [
      "Spuma care se formează la fierbere trebuie luată — dă un gust neplăcut.",
      "Borșul se adaugă doar la final și nu se mai fierbe mult după.",
      "Leușteanul se pune doar la servire, proaspăt.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "carne de miel cu os" },
      { qty: 2, unit: "buc", name: "cepe" },
      { qty: 2, unit: "buc", name: "morcovi" },
      { qty: 1, unit: "buc", name: "păstârnac" },
      { qty: 1, unit: "buc", name: "țelină mică" },
      { qty: 2, unit: "buc", name: "roșii" },
      { qty: 200, unit: "ml", name: "borș acru" },
      { qty: 1, unit: "legătură", name: "leuștean proaspăt" },
      { qty: 2, unit: "buc", name: "ouă (pentru dresire)" },
      { qty: 100, unit: "ml", name: "smântână (pentru dresire)" },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Pune carnea într-o oală cu 3 litri de apă rece. Pune pe foc.", tip: null },
      { text: "Când începe să fiarbă, ia spuma care se formează la suprafață.", tip: "Asta e cheia unei ciorbe limpezi." },
      { text: "Adaugă ceapa tăiată mărunt, morcovii, păstârnacul și țelina tăiate cubulețe. Fierbe la foc mic 1 oră.", tip: null },
      { text: "Adaugă roșiile tăiate (sau 2 linguri bulion). Fierbe încă 20 minute.", tip: null },
      { text: "Încălzește borșul separat (nu-l fierbe). Adaugă-l în ciorbă și amestecă.", tip: "Borșul fiert devine amar." },
      { text: "Bate ouăle cu smântâna. Temperează cu câteva linguri de supă caldă, apoi toarnă în oală amestecând continuu.", tip: "Temperarea previne tăierea ouălor." },
      { text: "Potrivește de sare și piper. Servește cu leuștean proaspăt tăiat fin.", tip: null },
    ],
    variants: [
      { id: "miel", label: "De Miel" },
      {
        id: "pui",
        label: "De Pui",
        baseIngredients: [
          { qty: 500, unit: "g", name: "carne de pui (pulpe, aripi)" },
          { qty: 2, unit: "buc", name: "cepe" },
          { qty: 2, unit: "buc", name: "morcovi" },
          { qty: 1, unit: "buc", name: "păstârnac" },
          { qty: 1, unit: "buc", name: "țelină mică" },
          { qty: 2, unit: "buc", name: "roșii" },
          { qty: 200, unit: "ml", name: "borș acru" },
          { qty: 1, unit: "legătură", name: "leuștean proaspăt" },
          { qty: 2, unit: "buc", name: "ouă (pentru dresire)" },
          { qty: 100, unit: "ml", name: "smântână (pentru dresire)" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
        ],
      },
      {
        id: "legume",
        label: "De Legume",
        baseIngredients: [
          { qty: 2, unit: "buc", name: "cepe" },
          { qty: 2, unit: "buc", name: "morcovi" },
          { qty: 1, unit: "buc", name: "păstârnac" },
          { qty: 1, unit: "buc", name: "țelină mică" },
          { qty: 2, unit: "buc", name: "roșii" },
          { qty: 2, unit: "buc", name: "cartofi" },
          { qty: 1, unit: "buc", name: "dovlecel" },
          { qty: 100, unit: "g", name: "fasole verde" },
          { qty: 200, unit: "ml", name: "borș acru" },
          { qty: 1, unit: "legătură", name: "leuștean proaspăt" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
        ],
      },
    ],
  },
  {
    id: "sarmale",
    name: "Sarmale în Foi de Varză",
    icon: "🫔",
    description: "Sarmalele — mândria bucătăriei românești. Rulouri de carne tocată în foi de varză, gătite lent.",
    prepTime: "PT45M",
    prepLabel: "45 min",
    cookTime: "PT3H",
    cookLabel: "3h",
    totalTime: "PT4H",
    totalLabel: "~4h",
    servings: 30,
    servingsUnit: "sarmale",
    calories: 180,
    difficulty: "Avansat",
    difficultyColor: "text-red-400",
    healthySwaps: [
      { match: "carne tocată de porc", swap: "700g carne tocată de curcan + 300g porc" },
      { match: "afumătură", swap: "100g afumătură slabă (redusă la jumătate)" },
      { match: "orez (spălat)", swap: "80g orez brun + 20g orez alb" },
    ],
    healthyCalories: 145,
    healthyNote: "Curcanul în loc de porc pur reduce grăsimile saturate cu ~35%. Orezul brun triplează fibra.",
    tips: [
      "Sarmalele sunt și mai bune a doua zi, reîncălzite.",
      "Foile de varză prea sărate se spală în apă caldă.",
      "Aranjează-le strâns în oală — nu le lăsa să se desfacă.",
      "Gătirea lentă la cuptor e secretul sarmalelor perfecte.",
    ],
    baseIngredients: [
      { qty: 1, unit: "buc", name: "varză murată mare (sau foi de varză)" },
      { qty: 1, unit: "kg", name: "carne tocată de porc" },
      { qty: 300, unit: "g", name: "ceapă (tocată mărunt)" },
      { qty: 100, unit: "g", name: "orez (spălat)" },
      { qty: 200, unit: "g", name: "afumătură (costiță, kaiser)" },
      { qty: 500, unit: "ml", name: "bulion de roșii (sau suc de roșii)" },
      { qty: 2, unit: "linguri", name: "boia dulce" },
      { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru uscat" : m === 1 ? "1 lingurită cimbru uscat" : `${Math.round(m)} lingurițe cimbru uscat` },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
      { qty: 3, unit: "buc", name: "foi de dafin" },
    ],
    filling: [],
    steps: [
      { text: "Desfă frunzele de varză murată. Taie nervura groasă de pe fiecare frunză.", tip: null },
      { text: "Amestecă carnea tocată cu ceapa, orezul spălat, boiaua, cimbrul, sare și piper.", tip: "Orezul se pune crud — se gătește în sarma." },
      { text: "Pune o lingură de compoziție pe fiecare frunză și rulează strâns, îndoind capetele.", tip: "Sarmalele mici sunt mai gustoase decât cele mari." },
      { text: "Într-o oală mare, pune un strat de varză tăiată fâșii pe fund.", tip: null },
      { text: "Aranjează sarmalele strâns, în straturi. Presară felii de afumătură și foi de dafin între straturi.", tip: null },
      { text: "Toarnă bulionul amestecat cu apă (cât să acopere sarmalele).", tip: null },
      { text: "Acoperă cu un strat de varză tăiată. Pune capac sau folie.", tip: null },
      { text: "Gătește la 180°C în cuptor 2.5-3 ore. Verifică lichidul ocazional.", tip: "Nu amesteca — doar scutură ușor oala." },
      { text: "Servește cu smântână și mămăligă caldă.", tip: null },
    ],
    variants: [
      { id: "porc", label: "Cu Porc" },
      {
        id: "porc-vita",
        label: "Porc + Vită",
        baseIngredients: [
          { qty: 1, unit: "buc", name: "varză murată mare" },
          { qty: 500, unit: "g", name: "carne tocată de porc" },
          { qty: 500, unit: "g", name: "carne tocată de vită" },
          { qty: 300, unit: "g", name: "ceapă (tocată mărunt)" },
          { qty: 100, unit: "g", name: "orez (spălat)" },
          { qty: 200, unit: "g", name: "afumătură (costiță)" },
          { qty: 500, unit: "ml", name: "bulion de roșii" },
          { qty: 2, unit: "linguri", name: "boia dulce" },
          { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru uscat" : m === 1 ? "1 lingurită cimbru uscat" : `${Math.round(m)} lingurițe cimbru uscat` },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 3, unit: "buc", name: "foi de dafin" },
        ],
      },
      {
        id: "foi-vita",
        label: "În Foi de Viță",
        baseIngredients: [
          { qty: 50, unit: "buc", name: "foi de viță murată (sau proaspete opărite)" },
          { qty: 800, unit: "g", name: "carne tocată amestec (porc + vită)" },
          { qty: 300, unit: "g", name: "ceapă (tocată mărunt)" },
          { qty: 100, unit: "g", name: "orez (spălat)" },
          { qty: 200, unit: "g", name: "afumătură (costiță)" },
          { qty: 500, unit: "ml", name: "suc de roșii" },
          { qty: 2, unit: "linguri", name: "boia dulce" },
          { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru uscat" : m === 1 ? "1 lingurită cimbru uscat" : `${Math.round(m)} lingurițe cimbru uscat` },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 3, unit: "buc", name: "foi de dafin" },
        ],
        tips: ["Foile de viță murată se desărează în apă caldă 30 de minute.", "Sarmalele în foi de viță sunt mai mici și mai delicate.", "Se gătesc mai repede — verifică după 2 ore."],
      },
      {
        id: "vegetariene",
        label: "Vegetariene",
        baseIngredients: [
          { qty: 1, unit: "buc", name: "varză murată mare" },
          { qty: 300, unit: "g", name: "orez cu bob lung" },
          { qty: 300, unit: "g", name: "ciuperci (tocate mărunt)" },
          { qty: 200, unit: "g", name: "morcovi (rasi)" },
          { qty: 300, unit: "g", name: "ceapă (tocată mărunt)" },
          { qty: 100, unit: "g", name: "ardei gras roșu (tocat)" },
          { qty: 500, unit: "ml", name: "suc de roșii" },
          { qty: 3, unit: "linguri", name: "ulei de măsline" },
          { qty: 2, unit: "linguri", name: "boia dulce" },
          { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru uscat" : m === 1 ? "1 lingurită cimbru uscat" : `${Math.round(m)} lingurițe cimbru uscat` },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
          { qty: 3, unit: "buc", name: "foi de dafin" },
        ],
        steps: [
          { text: "Desfă frunzele de varză.", tip: null },
          { text: "Călește ceapa, morcovii și ardeiul în ulei 5 minute.", tip: null },
          { text: "Adaugă ciupercile și mai călește 5 minute până scade apa.", tip: "Ciupercile trebuie să fie uscate." },
          { text: "Amestecă cu orezul crud, boiala, cimbrul, sare și piper.", tip: "Orezul se gătește în sarma." },
          { text: "Rulează sarmalele în foi de varză.", tip: "Sarmalele vegetariene pot fi mai mici." },
          { text: "Aranjează în straturi în oală cu suc de roșii.", tip: null },
          { text: "Gătește la 180°C 2-2.5 ore.", tip: null },
          { text: "Servește cu smântână sau iaurt grecesc.", tip: null },
        ],
        tips: ["Fără carne, sarmalele trebuie condimentate mai generos.", "Adaugă 1 lingură de sos de soia pentru umami."],
      },
    ],
  },
  // ──── NEW RECIPES (9-20) ────────────────────────────────────────────────
  {
    id: "piftie",
    name: "Piftie de Pui",
    icon: "🍗",
    description: "Piftie tradițională transparentă, cu carne fragedă de pui și usturoi — aperitivul perfect rece.",
    prepTime: "PT20M",
    prepLabel: "20 min",
    cookTime: "PT3H",
    cookLabel: "3h",
    totalTime: "PT6H",
    totalLabel: "~6h (cu răcire)",
    servings: 10,
    servingsUnit: "porții",
    calories: 150,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [],
    healthyCalories: 150,
    healthyNote: "Piftia e în mod natural săracă în calorii și bogată în colagen. Nicio modificare necesară.",
    tips: [
      "Picioarele de pui sunt esențiale — ele dau gelatina naturală.",
      "Fierbe la foc mic, nu clocotit — zeama trebuie să rămână limpede.",
      "Usturoiul se adaugă doar la final, nu se fierbe.",
    ],
    baseIngredients: [
      { qty: 1, unit: "kg", name: "pulpe și aripi de pui" },
      { qty: 500, unit: "g", name: "picioare de pui (pentru gelatină)" },
      { qty: 2, unit: "buc", name: "morcovi" },
      { qty: 1, unit: "buc", name: "ceapă mare" },
      { qty: 1, unit: "buc", name: "păstârnac" },
      { qty: 6, unit: "căței", name: "usturoi" },
      { qty: 3, unit: "buc", name: "foi de dafin" },
      { qty: 10, unit: "buc", name: "boabe de piper" },
      { qty: null, unit: "", name: "sare după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Spală bine carnea și picioarele de pui. Pune-le într-o oală mare cu apă rece (3-4 litri).", tip: null },
      { text: "Adaugă morcovii, ceapa, păstârnacul, foile de dafin și boabele de piper.", tip: null },
      { text: "Fierbe la foc mic 2.5-3 ore. Ia spuma periodic. Zeama trebuie să scadă la jumătate.", tip: "Focul mic e esențial — altfel zeama devine tulbure." },
      { text: "Scoate carnea și separă-o de oase. Rupe în bucăți mici.", tip: null },
      { text: "Strecoară zeama printr-un tifon sau sită fină.", tip: null },
      { text: "Pisează usturoiul cu puțină sare și adaugă-l în zeama strecurată.", tip: null },
      { text: "Pune bucățile de carne în forme/castroane. Toarnă zeama peste.", tip: "Adaugă și rondele de morcov fiert pentru decor." },
      { text: "Lasă la frigider minim 4-6 ore (peste noapte ideal) până se întărește.", tip: null },
    ],
    variants: [
      { id: "pui", label: "De Pui" },
      {
        id: "porc",
        label: "De Porc",
        baseIngredients: [
          { qty: 1, unit: "kg", name: "ciolan de porc (cu os)" },
          { qty: 500, unit: "g", name: "picioare de porc" },
          { qty: 2, unit: "buc", name: "morcovi" },
          { qty: 1, unit: "buc", name: "ceapă mare" },
          { qty: 1, unit: "buc", name: "păstârnac" },
          { qty: 8, unit: "căței", name: "usturoi" },
          { qty: 3, unit: "buc", name: "foi de dafin" },
          { qty: 10, unit: "buc", name: "boabe de piper" },
          { qty: null, unit: "", name: "sare după gust", scalable: false },
        ],
      },
    ],
  },
  {
    id: "mamaliga",
    name: "Mămăligă Tradițională",
    icon: "🌽",
    description: "Mămăliga cremoasă, perfectă alături de sarmale, friptură sau brânză cu smântână.",
    prepTime: "PT5M",
    prepLabel: "5 min",
    cookTime: "PT25M",
    cookLabel: "25 min",
    totalTime: "PT30M",
    totalLabel: "~30 min",
    servings: 6,
    servingsUnit: "porții",
    calories: 200,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "unt (opțional, la final)", swap: "1 lingură ulei de măsline extra-virgin" },
    ],
    healthyCalories: 185,
    healthyNote: "Mămăliga e un carbohidrat complex, fără gluten. Uleiul de măsline în loc de unt = grăsimi mai sănătoase.",
    tips: [
      "Amestecă continuu ca să nu facă cocoloașe.",
      "Mălai+apa=1:3 ca proporție perfectă.",
      "Se răstoarnă pe un fundal de lemn și se taie cu ața.",
    ],
    baseIngredients: [
      { qty: 400, unit: "g", name: "mălai (griș de porumb)" },
      { qty: 1.2, unit: "l", name: "apă" },
      { qty: 1, unit: "lingurită", name: "sare", textFn: (m) => m <= 0.5 ? "½ lingurită sare" : m === 1 ? "1 lingurită sare" : `${Math.round(m)} lingurițe sare` },
      { qty: 30, unit: "g", name: "unt (opțional, la final)" },
    ],
    filling: [],
    steps: [
      { text: "Pune apa cu sare la fiert într-o oală cu fund gros.", tip: null },
      { text: "Când clocotește, adaugă mălaiul în ploaie, amestecând continuu cu telul.", tip: "Toarnă mălaiul într-un fir subțire — așa eviți cocoloașele." },
      { text: "Redu focul la minim. Amestecă cu o lingură de lemn 20-25 minute.", tip: "Mămăliga e gata când se desprinde de pereții oalei." },
      { text: "Adaugă untul la final și amestecă. Răstoarnă pe un tocător de lemn.", tip: null },
    ],
  },
  {
    id: "cartofi-cuptor",
    name: "Cartofi la Cuptor cu Rozmarin",
    icon: "🥔",
    description: "Cartofi aurii și crocanți la exterior, pufoși la interior — garnitura perfectă pentru orice friptură de Paște.",
    prepTime: "PT10M",
    prepLabel: "10 min",
    cookTime: "PT45M",
    cookLabel: "45 min",
    totalTime: "PT1H",
    totalLabel: "~1h",
    servings: 6,
    servingsUnit: "porții",
    calories: 190,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "ulei de măsline", swap: "2 linguri ulei de măsline (redus la jumătate)" },
    ],
    healthyCalories: 155,
    healthyNote: "Cartofii la cuptor cu mai puțin ulei sunt la fel de crocanți dacă sunt tăiați subțiri.",
    tips: [
      "Cartofii tăiați mai mici se rumenesc mai repede.",
      "Nu îi suprapune în tavă — au nevoie de spațiu.",
      "Întoarce-i o dată la jumătatea timpului.",
    ],
    baseIngredients: [
      { qty: 1, unit: "kg", name: "cartofi (tăiați în sferturi)" },
      { qty: 4, unit: "linguri", name: "ulei de măsline" },
      { qty: 4, unit: "căței", name: "usturoi (zdrobiți)" },
      { qty: 3, unit: "ramuri", name: "rozmarin proaspăt" },
      { qty: null, unit: "", name: "sare, piper și boia dulce după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Preîncălzește cuptorul la 200°C. Curăță și taie cartofii în sferturi sau cuburi mari.", tip: null },
      { text: "Amestecă cartofii cu uleiul, usturoiul zdrobit, rozmarinul, sare, piper și boia.", tip: "Amestecă bine — fiecare cartof trebuie uns cu ulei." },
      { text: "Întinde cartofii într-un singur strat pe o tavă mare tapetată cu hârtie de copt.", tip: "Nu-i suprapune — altfel se aburesc în loc să se rumenească." },
      { text: "Coace 40-45 minute, întorcând o dată la jumătate, până sunt aurii și crocanți.", tip: null },
    ],
  },
  {
    id: "chec",
    name: "Chec Pufos",
    icon: "🍰",
    description: "Chec simplu și pufos, perfect pentru dimineața de Paște. Se poate face cu cacao, stafide sau lămâie.",
    prepTime: "PT15M",
    prepLabel: "15 min",
    cookTime: "PT45M",
    cookLabel: "45 min",
    totalTime: "PT1H",
    totalLabel: "~1h",
    servings: 12,
    servingsUnit: "felii",
    calories: 260,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "zahăr", swap: "150g eritritol + 50g miere" },
      { match: "făină", swap: "200g făină integrală + 50g făină de migdale" },
      { match: "ulei", swap: "80ml ulei + 20ml iaurt grecesc" },
    ],
    healthyCalories: 195,
    healthyNote: "Înlocuirile reduc caloriile cu ~25% și adaugă fibră și proteine.",
    tips: [
      "Toate ingredientele la temperatura camerei = chec mai pufos.",
      "Nu deschide cuptorul în primele 25 minute.",
      "Testează cu scobitoarea — trebuie să iasă curată.",
    ],
    baseIngredients: [
      { qty: 250, unit: "g", name: "făină" },
      { qty: 200, unit: "g", name: "zahăr" },
      { qty: 4, unit: "buc", name: "ouă" },
      { qty: 100, unit: "ml", name: "ulei" },
      { qty: 100, unit: "ml", name: "lapte" },
      { qty: 1, unit: "buc", name: "praf de copt" },
      { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
      { qty: null, unit: "", name: "sare (un vârf de cuțit)", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Preîncălzește cuptorul la 170°C. Unge o formă de chec cu unt și tapetează cu făină.", tip: null },
      { text: "Separă ouăle. Bate albușurile spumă tare cu un praf de sare.", tip: null },
      { text: "Bate gălbenușurile cu zahărul până devin cremoase. Adaugă uleiul și laptele.", tip: null },
      { text: "Adaugă făina cernută cu praful de copt și vanilia. Amestecă ușor.", tip: null },
      { text: "Încorporează albușurile bătute cu mișcări de jos în sus — nu amesteca circular.", tip: "Albușurile dau aerul din chec — tratează-i cu grijă." },
      { text: "Toarnă în formă. Coace 40-45 minute. Lasă să se răcească în formă 10 minute.", tip: null },
    ],
    variants: [
      { id: "simplu", label: "Simplu" },
      {
        id: "cacao",
        label: "Cu Cacao",
        baseIngredients: [
          { qty: 220, unit: "g", name: "făină" },
          { qty: 200, unit: "g", name: "zahăr" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 100, unit: "ml", name: "ulei" },
          { qty: 100, unit: "ml", name: "lapte" },
          { qty: 1, unit: "buc", name: "praf de copt" },
          { qty: 40, unit: "g", name: "cacao" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: null, unit: "", name: "sare (un vârf de cuțit)", scalable: false },
        ],
      },
      {
        id: "stafide",
        label: "Cu Stafide",
        baseIngredients: [
          { qty: 250, unit: "g", name: "făină" },
          { qty: 200, unit: "g", name: "zahăr" },
          { qty: 4, unit: "buc", name: "ouă" },
          { qty: 100, unit: "ml", name: "ulei" },
          { qty: 100, unit: "ml", name: "lapte" },
          { qty: 1, unit: "buc", name: "praf de copt" },
          { qty: 100, unit: "g", name: "stafide (înmuiate în rom)" },
          { qty: 1, unit: "lingurită", name: "esență de vanilie", textFn: (m) => m <= 0.5 ? "½ lingurită esență de vanilie" : m === 1 ? "1 lingurită esență de vanilie" : `${Math.round(m)} lingurițe esență de vanilie` },
          { qty: null, unit: "", name: "sare (un vârf de cuțit)", scalable: false },
        ],
      },
    ],
  },
  {
    id: "placinta-branza",
    name: "Plăcintă cu Brânză și Smântână",
    icon: "🥧",
    description: "Plăcintă pufoasă cu brânză sărată și smântână — gustarea ideală de Paște, caldă sau rece.",
    prepTime: "PT30M",
    prepLabel: "30 min",
    cookTime: "PT35M",
    cookLabel: "35 min",
    totalTime: "PT1H10M",
    totalLabel: "~1h 10min",
    servings: 8,
    servingsUnit: "porții",
    calories: 310,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "smântână", swap: "iaurt grecesc gras (10%)" },
      { match: "unt (topit, pentru uns foile)", swap: "ulei de măsline pentru uns foile" },
    ],
    healthyCalories: 255,
    healthyNote: "Iaurtul grec are același gust cremos ca smântâna cu 50% mai puțin grăsime.",
    tips: [
      "Brânza telemea e perfectă — sărată natural.",
      "Foile de plăcintă din comerț merg foarte bine.",
      "Unge fiecare foaie cu unt topit pentru crustă.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "foi de plăcintă (sau aluat)" },
      { qty: 400, unit: "g", name: "brânză telemea (sau urdă)" },
      { qty: 200, unit: "g", name: "smântână" },
      { qty: 3, unit: "buc", name: "ouă" },
      { qty: 80, unit: "g", name: "unt (topit, pentru uns foile)" },
      { qty: null, unit: "", name: "sare după gust (dacă brânza nu e sărată)", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Preîncălzește cuptorul la 180°C. Unge o tavă rotundă cu unt.", tip: null },
      { text: "Zdrobește brânza cu furculița. Amestecă cu smântâna și ouăle bătute.", tip: "Gustă amestecul — dacă brânza e sărată, nu mai adăuga sare." },
      { text: "Întinde o foaie de plăcintă, unge cu unt topit. Suprapune 2-3 foi.", tip: null },
      { text: "Pune un strat de compoziție, apoi alt strat de foi unse cu unt. Repetă.", tip: null },
      { text: "Termină cu un strat de foi deasupra. Unge cu unt topit și puțin ou bătut.", tip: null },
      { text: "Coace 30-35 minute până devine aurie. Servește caldă.", tip: null },
    ],
    variants: [
      { id: "telemea", label: "Cu Telemea" },
      {
        id: "urda",
        label: "Cu Urdă Dulce",
        baseIngredients: [
          { qty: 500, unit: "g", name: "foi de plăcintă" },
          { qty: 400, unit: "g", name: "urdă proaspătă" },
          { qty: 200, unit: "g", name: "smântână" },
          { qty: 3, unit: "buc", name: "ouă" },
          { qty: 80, unit: "g", name: "unt (topit)" },
          { qty: 50, unit: "g", name: "zahăr" },
          { qty: 50, unit: "g", name: "stafide" },
        ],
      },
    ],
  },
  {
    id: "strudel-mere",
    name: "Strudel cu Mere",
    icon: "🍎",
    description: "Strudel cu mere, scorțișoară și nucă — desertul aromat și crocant perfect pentru masa de Paște.",
    prepTime: "PT25M",
    prepLabel: "25 min",
    cookTime: "PT35M",
    cookLabel: "35 min",
    totalTime: "PT1H",
    totalLabel: "~1h",
    servings: 8,
    servingsUnit: "porții",
    calories: 250,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "zahăr", swap: "60g eritritol + mere mai dulci (Fuji/Gala)" },
      { match: "unt (topit)", swap: "50g unt topit + 30g ulei de cocos" },
      { match: "pesmet (prăjit în unt)", swap: "pesmet din biscuiți integrali prăjiți fără unt" },
    ],
    healthyCalories: 195,
    healthyNote: "Merele dulci reduc nevoia de zahăr adăugat. Varianta cu eritritol e prietenoasă cu diabeticii.",
    tips: [
      "Merele Ionatan sau Granny Smith sunt cele mai bune — acrișoare.",
      "Pesmetul absoarbe sucul merelor — nu sări peste el.",
      "Servește cald, cu zahăr pudră presărat deasupra.",
    ],
    baseIngredients: [
      { qty: 1, unit: "buc", name: "pachet foi de plăcintă subțiri" },
      { qty: 1, unit: "kg", name: "mere (curățate, rase pe răzătoare)" },
      { qty: 100, unit: "g", name: "zahăr" },
      { qty: 50, unit: "g", name: "nucă măcinată" },
      { qty: 50, unit: "g", name: "pesmet (prăjit în unt)" },
      { qty: 80, unit: "g", name: "unt (topit)" },
      { qty: 1, unit: "lingurită", name: "scorțișoară", textFn: (m) => m <= 0.5 ? "½ lingurită scorțișoară" : m === 1 ? "1 lingurită scorțișoară" : `${Math.round(m)} lingurițe scorțișoară` },
      { qty: null, unit: "", name: "zahăr pudră pentru presărat", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Preîncălzește cuptorul la 180°C. Rade merele și stoarce excesul de suc.", tip: "Merele prea ude fac strudelul moale." },
      { text: "Amestecă merele cu zahărul, nuca, scorțișoara.", tip: null },
      { text: "Prăjește pesmetul în 20g unt până devine auriu.", tip: null },
      { text: "Întinde o foaie, unge cu unt topit, presară pesmet. Suprapune 2-3 foi.", tip: null },
      { text: "Pune compoziția de mere de-a lungul unui capăt. Rulează strâns.", tip: "Îndoaie capetele ca să nu curgă sucul." },
      { text: "Unge ruloul cu unt topit. Coace 30-35 minute până devine auriu.", tip: null },
      { text: "Presară zahăr pudră la servire. Se servește cald sau la temperatura camerei.", tip: null },
    ],
  },
  {
    id: "prajitura-nuca",
    name: "Prăjitură cu Nucă și Cremă",
    icon: "🍫",
    description: "Prăjitură festivă cu blat pufos de nucă și cremă de ciocolată — perfectă pentru masa dulce de Paște.",
    prepTime: "PT30M",
    prepLabel: "30 min",
    cookTime: "PT30M",
    cookLabel: "30 min",
    totalTime: "PT1H30M",
    totalLabel: "~1.5h",
    servings: 16,
    servingsUnit: "porții",
    calories: 340,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "zahăr", swap: "150g eritritol" },
      { match: "unt moale", swap: "150g unt + 50g iaurt grecesc" },
      { match: "zahăr pudră", swap: "70g eritritol pudră" },
    ],
    healthyCalories: 265,
    healthyNote: "Eritritolul păstrează textura cremei. Reducere de ~22% calorii față de original.",
    tips: [
      "Nuca trebuie măcinată fin — dar nu praf.",
      "Crema se întinde pe blatul rece — altfel se topește.",
      "E mai bună a doua zi, după ce crema se întărește.",
    ],
    baseIngredients: [
      { qty: 6, unit: "buc", name: "ouă" },
      { qty: 200, unit: "g", name: "zahăr" },
      { qty: 200, unit: "g", name: "nucă măcinată" },
      { qty: 2, unit: "linguri", name: "făină" },
      { qty: 1, unit: "buc", name: "praf de copt" },
    ],
    filling: [
      { qty: 200, unit: "g", name: "ciocolată neagră" },
      { qty: 200, unit: "g", name: "unt moale" },
      { qty: 100, unit: "g", name: "zahăr pudră" },
      { qty: 3, unit: "linguri", name: "cacao" },
      { qty: 3, unit: "linguri", name: "lapte" },
    ],
    steps: [
      { text: "Separă ouăle. Bate albușurile spumă tare cu zahărul.", tip: null },
      { text: "Adaugă gălbenușurile pe rând, apoi nuca, făina și praful de copt.", tip: "Amestecă ușor, de jos în sus." },
      { text: "Toarnă în tavă tapetată (30x40cm). Coace la 170°C, 25-30 minute.", tip: null },
      { text: "Crema: topește ciocolata la bain-marie. Bate untul cu zahărul pudră, adaugă cacaua, laptele și ciocolata topită.", tip: null },
      { text: "Taie blatul răcit în două pe orizontală. Întinde crema pe un blat, suprapune celălalt.", tip: null },
      { text: "Decorează cu restul de cremă deasupra. Refrigerează 2 ore.", tip: null },
    ],
  },
  {
    id: "mici",
    name: "Mici (Mititei)",
    icon: "🌭",
    description: "Mici tradiționali românești, aromatic cu usturoi și cimbru — perfecți la grătar pentru o zi de Paște.",
    prepTime: "PT20M",
    prepLabel: "20 min",
    cookTime: "PT15M",
    cookLabel: "15 min",
    totalTime: "PT4H",
    totalLabel: "~4h (cu odihnă)",
    servings: 20,
    servingsUnit: "mici",
    calories: 200,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "carne tocată de porc", swap: "250g carne tocată de curcan" },
      { match: "carne tocată de oaie (sau vită)", swap: "250g carne tocată de vită slabă (5% grăsime)" },
    ],
    healthyCalories: 155,
    healthyNote: "Curcanul în loc de porc și vița slabă reduc grăsimile totale cu ~40% fără a pierde din savoare.",
    tips: [
      "Carnea trebuie obligatoriu lăsată la frigider minim 3 ore.",
      "Mâinile ude cu apă rece ajută la modelat.",
      "Nu-i apăsa pe grătar — pierd sucul.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "carne tocată de vită" },
      { qty: 250, unit: "g", name: "carne tocată de porc" },
      { qty: 250, unit: "g", name: "carne tocată de oaie (sau vită)" },
      { qty: 6, unit: "căței", name: "usturoi (pisat)" },
      { qty: 1, unit: "lingurită", name: "cimbru uscat", textFn: (m) => m <= 0.5 ? "½ lingurită cimbru" : m === 1 ? "1 lingurită cimbru" : `${Math.round(m)} lingurițe cimbru` },
      { qty: 1, unit: "lingurită", name: "boia dulce", textFn: (m) => m <= 0.5 ? "½ lingurită boia" : m === 1 ? "1 lingurită boia" : `${Math.round(m)} lingurițe boia` },
      { qty: 0.5, unit: "lingurită", name: "bicarbonat de sodiu", textFn: (m) => m <= 0.5 ? "un vârf de cuțit bicarbonat" : m === 1 ? "½ lingurită bicarbonat" : `${Math.round(m * 0.5)} lingurițe bicarbonat` },
      { qty: 100, unit: "ml", name: "apă minerală carbogazoasă" },
      { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Amestecă toate tipurile de carne tocată într-un bol mare.", tip: null },
      { text: "Adaugă usturoiul pisat, cimbrul, boiala, bicarbonatul, sare și piper. Amestecă bine.", tip: null },
      { text: "Adaugă apa minerală treptat, frământând energic 5-10 minute.", tip: "Carnea trebuie frământată bine — asta dă textura specifică." },
      { text: "Acoperă cu folie și lasă la frigider minim 3 ore (ideal peste noapte).", tip: null },
      { text: "Cu mâinile ude, modelează mici de ~8cm lungime.", tip: null },
      { text: "Pune pe grătarul încins (sau tigaie cu puțin ulei). Gătește 3-4 minute pe fiecare parte.", tip: "Nu-i întoarce prea des — formează crustă." },
      { text: "Servește fierbinți cu muștar și pâine proaspătă.", tip: null },
    ],
  },
  {
    id: "salata-vinete",
    name: "Salată de Vinete",
    icon: "🍆",
    description: "Salată de vinete afumate, cremoasă și ușoară — aperitivul de vară perfect și pentru masa de Paște.",
    prepTime: "PT15M",
    prepLabel: "15 min",
    cookTime: "PT40M",
    cookLabel: "40 min",
    totalTime: "PT2H",
    totalLabel: "~2h (cu scurgere)",
    servings: 6,
    servingsUnit: "porții",
    calories: 120,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "ulei de floarea-soarelui", swap: "3 linguri ulei de măsline extra-virgin" },
    ],
    healthyCalories: 105,
    healthyNote: "Salata de vinete e deja una din cele mai sănătoase rețete! Uleiul de măsline adaugă omega-9.",
    tips: [
      "Vinetele coapte pe flacără au cel mai bun gust afumat.",
      "Scurge-le bine — minim 1 oră — altfel salata e apoasă.",
      "Taie cu cuțitul de lemn sau ceramic — cel de metal le oxidează.",
      "Ceapa se pune doar la final, crudă și tocată foarte mărunt.",
    ],
    baseIngredients: [
      { qty: 3, unit: "buc", name: "vinete mari" },
      { qty: 1, unit: "buc", name: "ceapă mică (tocată fin)" },
      { qty: 4, unit: "linguri", name: "ulei de floarea-soarelui" },
      { qty: null, unit: "", name: "sare după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Spală vinetele și înțeapă-le cu furculița. Coace-le pe flacăra aragazului sau la cuptor (200°C, 30-40 min) până coaja se carbonizează.", tip: "Pe flacără directă dau cel mai bun gust afumat." },
      { text: "Pune vinetele fierbinți într-o strecurătoare, taie-le și lasă-le la scurs minim 1 oră.", tip: "Apăsă ușor cu o farfurie deasupra pentru mai multă scurgere." },
      { text: "Toacă vinetele cu un cuțit de lemn (sau ceramic) — nu folosi cuțit metalic.", tip: null },
      { text: "Adaugă uleiul treptat, amestecând ca la maioneză. Adaugă sare.", tip: null },
      { text: "La servire, adaugă ceapa tocată mărunt deasupra. Servește cu pâine proaspătă.", tip: null },
    ],
    variants: [
      { id: "simpla", label: "Simplă" },
      {
        id: "maioneza",
        label: "Cu Maioneză",
        baseIngredients: [
          { qty: 3, unit: "buc", name: "vinete mari" },
          { qty: 1, unit: "buc", name: "ceapă mică (tocată fin)" },
          { qty: 3, unit: "linguri", name: "maioneză" },
          { qty: 2, unit: "linguri", name: "ulei" },
          { qty: null, unit: "", name: "sare după gust", scalable: false },
        ],
      },
    ],
  },
  {
    id: "paine-casa",
    name: "Pâine de Casă",
    icon: "🍞",
    description: "Pâine de casă cu crustă crocantă și miez pufos — perfectă alături de orice fel de la masa de Paște.",
    prepTime: "PT20M",
    prepLabel: "20 min",
    cookTime: "PT40M",
    cookLabel: "40 min",
    totalTime: "PT3H",
    totalLabel: "~3h (cu dospire)",
    servings: 1,
    servingsUnit: "pâine",
    calories: 250,
    difficulty: "Mediu",
    difficultyColor: "text-yellow-400",
    healthySwaps: [
      { match: "făină albă", swap: "350g făină integrală + 150g făină albă" },
      { match: "ulei de măsline", swap: "1 lingură ulei de măsline (redus)" },
    ],
    healthyCalories: 210,
    healthyNote: "Făina integrală triplează fibra și reduce indicele glicemic. Crusta rămâne la fel de crocantă.",
    tips: [
      "Drojdia proaspătă dă cele mai bune rezultate.",
      "Aluatul trebuie frământat bine — minim 10 minute.",
      "Pune un bol cu apă în cuptor — crustă perfectă.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "făină albă" },
      { qty: 300, unit: "ml", name: "apă călduță" },
      { qty: 25, unit: "g", name: "drojdie proaspătă" },
      { qty: 1, unit: "lingurită", name: "sare", textFn: (m) => m <= 0.5 ? "½ lingurită sare" : m === 1 ? "1 lingurită sare" : `${Math.round(m)} lingurițe sare` },
      { qty: 1, unit: "lingurită", name: "zahăr", textFn: (m) => m <= 0.5 ? "½ lingurită zahăr" : m === 1 ? "1 lingurită zahăr" : `${Math.round(m)} lingurițe zahăr` },
      { qty: 2, unit: "linguri", name: "ulei de măsline" },
    ],
    filling: [],
    steps: [
      { text: "Dizolvă drojdia în apa călduță cu zahărul. Lasă 10 minute până face spumă.", tip: null },
      { text: "Pune făina cu sarea într-un bol. Adaugă drojdia dizolvată și uleiul.", tip: null },
      { text: "Frământă 10 minute până aluatul devine elastic și neted.", tip: "Aluatul e gata când nu se mai lipește de mâini." },
      { text: "Acoperă cu prosop și lasă la dospit 1-1.5 ore (până se dublează).", tip: null },
      { text: "Modelează o pâine rotundă. Pune pe tavă cu hârtie de copt. Crestează deasupra.", tip: null },
      { text: "Lasă la dospit încă 30 minute. Preîncălzește cuptorul la 220°C cu un bol de apă.", tip: null },
      { text: "Coace 35-40 minute. Pâinea e gata când sună gol la bătut pe fund.", tip: null },
    ],
  },
  {
    id: "salata-orientala",
    name: "Salată Orientală",
    icon: "🥚",
    description: "Salată simplă cu cartofi, ouă fierte și ceapă — garnitura tradițională ușoară de Paște.",
    prepTime: "PT15M",
    prepLabel: "15 min",
    cookTime: "PT25M",
    cookLabel: "25 min",
    totalTime: "PT1H",
    totalLabel: "~1h (cu răcire)",
    servings: 6,
    servingsUnit: "porții",
    calories: 180,
    difficulty: "Ușor",
    difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "ulei de măsline", swap: "2 linguri ulei de măsline (redus)" },
      { match: "oțet de vin", swap: "suc de lămâie proaspăt" },
    ],
    healthyCalories: 155,
    healthyNote: "Salata orientală e deja ușoară. Sucul de lămâie în loc de oțet = mai multă vitamina C.",
    tips: [
      "Cartofii trebuie fierți al dente — nu prea moi.",
      "Ceapa crudă se poate înmuia 10 min în apă cu oțet.",
      "Se servește rece — lasă minim 30 minute la frigider.",
    ],
    baseIngredients: [
      { qty: 600, unit: "g", name: "cartofi" },
      { qty: 4, unit: "buc", name: "ouă fierte tari" },
      { qty: 1, unit: "buc", name: "ceapă roșie" },
      { qty: 100, unit: "g", name: "măsline negre" },
      { qty: 4, unit: "linguri", name: "ulei de măsline" },
      { qty: 2, unit: "linguri", name: "oțet de vin" },
      { qty: null, unit: "", name: "sare, piper și boia dulce", scalable: false },
      { qty: null, unit: "", name: "pătrunjel proaspăt", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Fierbe cartofii în coajă, în apă cu sare, până sunt al dente. Răcește-i.", tip: null },
      { text: "Fierbe ouăle tari (10 minute). Răcește în apă rece și curăță.", tip: null },
      { text: "Curăță cartofii și taie-i rondele. Taie ouăle felii.", tip: null },
      { text: "Aranjează în straturi: cartofi, ouă, ceapă tăiată rondele, măsline.", tip: null },
      { text: "Stropește cu ulei și oțet. Presară sare, piper, boia.", tip: null },
      { text: "Decorează cu pătrunjel. Servește rece.", tip: null },
    ],
  },
  {
    id: "tort-ciocolata",
    name: "Tort de Ciocolată",
    icon: "🎂",
    description: "Tort festiv de ciocolată, cu blat umed și cremă ganache — desertul spectaculos de Paște.",
    prepTime: "PT30M",
    prepLabel: "30 min",
    cookTime: "PT35M",
    cookLabel: "35 min",
    totalTime: "PT2H",
    totalLabel: "~2h",
    servings: 12,
    servingsUnit: "porții",
    calories: 420,
    difficulty: "Avansat",
    difficultyColor: "text-red-400",
    healthySwaps: [
      { match: "zahăr", swap: "150g eritritol" },
      { match: "unt", swap: "150g unt + 50g piure de avocado" },
      { match: "smântână lichidă (33%)", swap: "200ml smântână lichidă 30% + 100ml lapte de cocos" },
    ],
    healthyCalories: 340,
    healthyNote: "Chiar și cu eritritol, tortul de ciocolată e o răsfățare ocazională. Avocado adaugă grăsimi mono-nesaturate.",
    tips: [
      "Ciocolata de calitate face diferența — minim 55% cacao.",
      "Blatul se prepară ușor — secretul e să nu-l coci prea mult.",
      "Crema ganache se face cu smântână fierbinte peste ciocolată — simplu!",
    ],
    baseIngredients: [
      { qty: 200, unit: "g", name: "ciocolată neagră (55%+)" },
      { qty: 200, unit: "g", name: "unt" },
      { qty: 200, unit: "g", name: "zahăr" },
      { qty: 4, unit: "buc", name: "ouă" },
      { qty: 100, unit: "g", name: "făină" },
      { qty: 30, unit: "g", name: "cacao" },
      { qty: 1, unit: "buc", name: "praf de copt" },
    ],
    filling: [
      { qty: 300, unit: "g", name: "ciocolată neagră (pentru ganache)" },
      { qty: 300, unit: "ml", name: "smântână lichidă (33%)" },
      { qty: 30, unit: "g", name: "unt" },
    ],
    steps: [
      { text: "Topește ciocolata cu untul la bain-marie. Lasă să se tempereze.", tip: null },
      { text: "Bate ouăle cu zahărul 5 minute. Adaugă ciocolata topită.", tip: null },
      { text: "Adaugă făina cernută cu cacaua și praful de copt. Amestecă delicat.", tip: null },
      { text: "Toarnă în formă rotundă (24cm) tapetată. Coace la 170°C, 30-35 minute.", tip: "Blatul trebuie să rămână ușor umed la mijloc." },
      { text: "Ganache: încălzește smântâna. Toarnă peste ciocolata ruptă bucăți. Amestecă. Adaugă untul.", tip: null },
      { text: "Lasă ganache-ul 1 oră la frigider. Taie blatul în 2. Întinde cremă între blaturi și pe exterior.", tip: null },
      { text: "Decorează cu fructe, bomboane sau ciocolată rasă. Refrigerează 2 ore.", tip: null },
    ],
  },
  // ──── NEW RECIPES (21-23) ────────────────────────────────────────────────
  {
    id: "pui-smantana-ciuperci",
    name: "Pui cu Sos de Smântână și Ciuperci",
    icon: "🍗",
    description: "Pui fraged în sos cremos de smântână cu ciuperci — fel principal elegant și rapid pentru masa de Paște.",
    prepTime: "PT15M", prepLabel: "15 min",
    cookTime: "PT35M", cookLabel: "35 min",
    totalTime: "PT50M", totalLabel: "~50 min",
    servings: 4, servingsUnit: "porții",
    calories: 380,
    difficulty: "Ușor", difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "smântână", swap: "iaurt grecesc gras + 2 linguri frișcă lichidă" },
      { match: "unt", swap: "ulei de măsline" },
    ],
    healthyCalories: 295,
    healthyNote: "Iaurtul grec înlocuiește smântâna cu 40% mai puțin grăsime fără a pierde cremozitatea.",
    tips: [
      "Nu fierbe sosul după ce adaugi smântâna — se taie.",
      "Ciupercile brune au un gust mai intens decât cele albe.",
      "Adaugă puțin vin alb pentru un sos mai complex.",
    ],
    baseIngredients: [
      { qty: 800, unit: "g", name: "piept sau pulpe de pui (dezosate)" },
      { qty: 400, unit: "g", name: "ciuperci brune (feliate)" },
      { qty: 1, unit: "buc", name: "ceapă mare" },
      { qty: 3, unit: "căței", name: "usturoi" },
      { qty: 300, unit: "ml", name: "smântână (30%)" },
      { qty: 2, unit: "linguri", name: "unt" },
      { qty: 2, unit: "linguri", name: "ulei de măsline" },
      { qty: 1, unit: "legătură", name: "pătrunjel proaspăt" },
      { qty: null, unit: "", name: "sare, piper și nucșoară după gust", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Taie puiul în bucăți medii. Condimentează cu sare și piper.", tip: null },
      { text: "Rumenește puiul în ulei + unt la foc mare 3-4 minute pe fiecare parte. Scoate și rezervă.", tip: "Foc mare = crustă aurie. Nu înghesui bucățile." },
      { text: "În aceeași tigaie, călește ceapa tocată 3 minute. Adaugă usturoiul.", tip: null },
      { text: "Adaugă ciupercile feliate. Gătește la foc mare 5-6 minute până se evaporă apa.", tip: "Ciupercile eliberează multă apă — răbdare." },
      { text: "Adaugă smântâna. Adu la fierbere ușoară, amestecând.", tip: "Foc mic după ce adaugi smântâna." },
      { text: "Pune puiul înapoi în sos. Gătește acoperit la foc mic 15 minute.", tip: null },
      { text: "Potrivește condimentele. Presară pătrunjel proaspăt. Servește cu mămăligă sau orez.", tip: null },
    ],
    variants: [
      { id: "smantana", label: "Cu Smântână" },
      {
        id: "vin-alb",
        label: "Cu Vin Alb",
        baseIngredients: [
          { qty: 800, unit: "g", name: "piept sau pulpe de pui (dezosate)" },
          { qty: 400, unit: "g", name: "ciuperci brune (feliate)" },
          { qty: 1, unit: "buc", name: "ceapă mare" },
          { qty: 3, unit: "căței", name: "usturoi" },
          { qty: 150, unit: "ml", name: "smântână (30%)" },
          { qty: 150, unit: "ml", name: "vin alb sec" },
          { qty: 2, unit: "linguri", name: "unt" },
          { qty: 2, unit: "linguri", name: "ulei de măsline" },
          { qty: 1, unit: "legătură", name: "cimbru proaspăt" },
          { qty: null, unit: "", name: "sare și piper după gust", scalable: false },
        ],
        stepsOverride: { 4: { text: "Adaugă vinul. Lasă să se evapore 3 minute. Adaugă smântâna.", tip: "Vinul deglajeaza tigaia — rade fundul cu o spatulă." } },
      },
    ],
  },
  {
    id: "oua-umplute",
    name: "Ouă Umplute cu Maioneză",
    icon: "🥚",
    description: "Clasicul aperitiv de Paște — ouă fierte umplute cu cremă de gălbenuș și maioneză, decorate cu boia.",
    prepTime: "PT20M", prepLabel: "20 min",
    cookTime: "PT10M", cookLabel: "10 min",
    totalTime: "PT40M", totalLabel: "~40 min (cu răcire)",
    servings: 6, servingsUnit: "porții (12 jumătăți)",
    calories: 195,
    difficulty: "Ușor", difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "maioneză", swap: "maioneză light + 1 lingură iaurt grecesc" },
    ],
    healthyCalories: 145,
    healthyNote: "Maioneza light + iaurt = aceeași textură cu ~25% mai puțin calorii.",
    tips: [
      "Ouăle fierte la 10 minute exact — gălbenușul perfect ferm.",
      "Răcește ouăle în apă cu gheață imediat după fierbere — coaja se curăță ușor.",
      "Crema umplutură trebuie să fie la temperatura camerei când o pui în poș.",
    ],
    baseIngredients: [
      { qty: 6, unit: "buc", name: "ouă" },
      { qty: 3, unit: "linguri", name: "maioneză" },
      { qty: 1, unit: "lingurită", name: "muștar" },
      { qty: null, unit: "", name: "sare, piper și boia pentru decor", scalable: false },
      { qty: null, unit: "", name: "pătrunjel proaspăt pentru decor", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Fierbe ouăle tari (10 minute de la clocot). Răcește imediat în apă cu gheață.", tip: "Apa cu gheață oprește gătirea și ușurează curățarea." },
      { text: "Curăță și taie ouăle în jumătate pe lungime.", tip: null },
      { text: "Scoate gălbenușurile cu grijă în un bol.", tip: null },
      { text: "Pisează gălbenușurile cu maioneza, muștarul, sare și piper până obții o cremă omogenă.", tip: "Cu furculița sau cu mixer la viteză mică." },
      { text: "Umple albușurile cu crema — cu lingurita sau cu un poș.", tip: "Poșul cu duză stelată dă un aspect elegant." },
      { text: "Presară boia dulce și decorează cu frunzulițe de pătrunjel. Refrigerează până la servire.", tip: null },
    ],
    variants: [
      { id: "clasic", label: "Clasic" },
      {
        id: "cu-ton",
        label: "Cu Ton",
        baseIngredients: [
          { qty: 6, unit: "buc", name: "ouă" },
          { qty: 1, unit: "conservă", name: "ton în ulei de măsline (80g, bine scurs)" },
          { qty: 2, unit: "linguri", name: "maioneză" },
          { qty: 1, unit: "lingurită", name: "capere (tocate, opțional)" },
          { qty: null, unit: "", name: "sare, piper și boia pentru decor", scalable: false },
        ],
        stepsOverride: { 3: { text: "Pisează gălbenușurile cu tonul scurs bine, maioneza, caperele, sare și piper.", tip: "Tonul trebuie scurs complet — altfel crema devine apoasă." } },
      },
      {
        id: "cu-avocado",
        label: "Cu Avocado",
        baseIngredients: [
          { qty: 6, unit: "buc", name: "ouă" },
          { qty: 1, unit: "buc", name: "avocado copt" },
          { qty: 1, unit: "lingurită", name: "suc de lămâie" },
          { qty: 1, unit: "lingurită", name: "muștar Dijon" },
          { qty: null, unit: "", name: "sare, piper și boia pentru decor", scalable: false },
        ],
        stepsOverride: { 3: { text: "Pisează gălbenușurile cu avocado, sucul de lămâie, muștar, sare și piper.", tip: "Avocado trebuie copt — se pisează ușor cu furculița." } },
        tips: ["Avocado se oxidează rapid — pregătește cu maxim 2 ore înainte.", "Sucul de lămâie încetinește oxidarea."],
      },
    ],
  },
  {
    id: "tiramisu",
    name: "Tiramisu Rapid",
    icon: "🍰",
    description: "Desert italian iubit de toți — piscoturi înmuiate în cafea, cremă de mascarpone și cacao pudră.",
    prepTime: "PT25M", prepLabel: "25 min",
    cookTime: "PT0M", cookLabel: "fără gătire",
    totalTime: "PT4H", totalLabel: "~4h (cu răcire)",
    servings: 8, servingsUnit: "porții",
    calories: 365,
    difficulty: "Ușor", difficultyColor: "text-green-400",
    healthySwaps: [
      { match: "mascarpone", swap: "200g mascarpone + 300g ricotta" },
      { match: "zahăr", swap: "50g eritritol" },
    ],
    healthyCalories: 285,
    healthyNote: "Ricotta are jumătate din caloriile mascarpone-ului. Eritritolul elimină zahărul complet.",
    tips: [
      "Albușurile bătute dau aerul din cremă — nu le omite.",
      "Cafeaua trebuie să fie rece când înmoi piscoturile.",
      "Cu cât stă mai mult la frigider, cu atât e mai bun.",
    ],
    baseIngredients: [
      { qty: 500, unit: "g", name: "mascarpone" },
      { qty: 4, unit: "buc", name: "ouă (separate)" },
      { qty: 80, unit: "g", name: "zahăr" },
      { qty: 200, unit: "ml", name: "cafea espresso rece" },
      { qty: 30, unit: "ml", name: "rom alimentar sau amaretto (opțional)" },
      { qty: 200, unit: "g", name: "piscoturi (Savoiardi)" },
      { qty: null, unit: "", name: "cacao pudră pentru presărat", scalable: false },
    ],
    filling: [],
    steps: [
      { text: "Separă ouăle. Bate gălbenușurile cu zahărul până devin albe și cremoase.", tip: null },
      { text: "Adaugă mascarpone-ul și amestecă ușor.", tip: "Nu amesteca prea tare — crema trebuie să rămână fermă." },
      { text: "Bate albușurile spumă tare cu un praf de sare. Incorporează ușor în crema de mascarpone.", tip: "Mișcări de jos în sus — nu circular." },
      { text: "Amestecă cafeaua cu romul (dacă folosești). Înmoaie rapid piscoturile — 2-3 secunde pe fiecare parte.", tip: "Nu înmuia prea mult — piscoturile devin moi și crema va fi umedă." },
      { text: "Pune un strat de piscoturi în formă. Acoperă cu jumătate din cremă.", tip: null },
      { text: "Repetă cu al doilea strat de piscoturi și restul cremei.", tip: null },
      { text: "Refrigerează minim 4 ore (ideal peste noapte). Presară cacao înainte de servire.", tip: "Cacao se presară chiar înainte de servire — altfel se umezește." },
    ],
    variants: [
      { id: "clasic", label: "Clasic" },
      {
        id: "fara-oua-crude",
        label: "Fără Ouă Crude",
        baseIngredients: [
          { qty: 500, unit: "g", name: "mascarpone" },
          { qty: 300, unit: "ml", name: "frișcă lichidă (33%)" },
          { qty: 80, unit: "g", name: "zahăr pudră" },
          { qty: 200, unit: "ml", name: "cafea espresso rece" },
          { qty: 30, unit: "ml", name: "rom alimentar (opțional)" },
          { qty: 200, unit: "g", name: "piscoturi (Savoiardi)" },
          { qty: null, unit: "", name: "cacao pudră pentru presărat", scalable: false },
        ],
        steps: [
          { text: "Bate frișca cu zahărul pudră până devine fermă.", tip: null },
          { text: "Incorporează mascarpone-ul în frișcă, amestecând ușor.", tip: null },
          { text: "Înmoaie piscoturile în cafea cu rom.", tip: null },
          { text: "Alternează straturi de piscoturi și cremă.", tip: null },
          { text: "Refrigerează minim 4 ore. Presară cacao la servire.", tip: null },
        ],
        tips: ["Varianta fără ouă crude e sigură pentru gravide și copii."],
      },
    ],
  },
];
